[package]
name="k-nucleotide"
version="0.0.0"
[[bin]]
name="knucleotide"
path="knucleotide.rs"
[dependencies]
futures="0.1.30"
itertools="*"
tokio-threadpool="*"
num="*"
hashbrown="*"
[profile.bench]
opt-level = 3
lto = true
