[package]
name="k-nucleotide"
version="0.0.0"
[[bin]]
name="knucleotide"
path="knucleotide.rs"
[dependencies]
futures="0.1.30"
futures-cpupool="*"
ordermap="*"
[profile.bench]
opt-level = 3
lto = true
